#language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
  - mongodb

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - sleep 15
  - mongo gamification --eval 'db.createUser({user:"root", pwd:"root", roles:[{role:"dbAdmin", db:"gamification"}]});'

script:
  - ./gradlew test
  #- ./gradlew test --tests "juja.microservices.integration.*"
  #- ./gradlew test --tests "juja.microservices.acceptance.*"

after_success:
  - ./gradlew buildDocker
 # - docker build -f Dockerfile -t gamification:latest .
  - docker images
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push juja/gamification
